from __future__ import annotations

import csv
import json
import os
import shutil
import stat
import subprocess
import sys
import sysconfig
from collections.abc import Callable
from pathlib import Path, PurePosixPath
from time import perf_counter
from typing import Any

from pkgreuse.domain.models import TransferKind


def normalized_absolute_path(path: str | Path) -> str:
    """
    Return a normalized absolute path without resolving it through
    the filesystem.
    """
    return os.path.normcase(os.path.abspath(os.fspath(path)))


def path_is_within(path: str | Path, root: str | Path) -> bool:
    """
    Check containment lexically using normalized absolute paths.

    Unlike Path.resolve(), this does not perform filesystem work for
    every checked path.
    """
    normalized_path = normalized_absolute_path(path)
    normalized_root = normalized_absolute_path(root)

    try:
        common_path = os.path.commonpath([normalized_path, normalized_root])
    except ValueError:
        # Different drives on Windows.
        return False

    return common_path == normalized_root


def target_site_packages() -> Path:
    """Return site-packages for the active target environment."""
    return Path(sysconfig.get_paths()["purelib"]).absolute()


def choose_donor(
    candidates: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Select a reusable donor.

    Prefer a donor on the same drive as the target because it can
    support hard links later.
    """
    target_environment = Path(sys.prefix).absolute()
    target_drive = os.path.splitdrive(str(target_environment))[0].casefold()

    usable_candidates: list[dict[str, Any]] = []

    for candidate in candidates:
        candidate_environment = Path(candidate["environment"]).absolute()

        if normalized_absolute_path(candidate_environment) == normalized_absolute_path(
            target_environment
        ):
            continue

        if candidate.get("editable"):
            continue

        record_path = candidate.get("record")

        if not record_path:
            continue

        if not os.path.isfile(record_path):
            continue

        usable_candidates.append(candidate)

    if not usable_candidates:
        raise RuntimeError(
            "No reusable donor was found. Candidates may be editable, "
            "missing RECORD metadata, or already installed in the target."
        )

    def donor_rank(
        candidate: dict[str, Any],
    ) -> tuple[int, int]:
        donor_drive = os.path.splitdrive(candidate["environment"])[0].casefold()

        same_drive = donor_drive == target_drive

        return (
            0 if same_drive else 1,
            len(candidate["environment"]),
        )

    usable_candidates.sort(key=donor_rank)

    return usable_candidates[0]


def record_path_parts(record_value: str) -> tuple[str, ...]:
    """
    Convert a forward-slash RECORD path into native path components.
    """
    return PurePosixPath(record_value).parts


def is_disposable_bytecode(record_value: str) -> bool:
    """Return True for Python-generated bytecode files."""
    path = PurePosixPath(record_value)

    if "__pycache__" in path.parts:
        return True

    return path.suffix.casefold() in {
        ".pyc",
        ".pyo",
    }


def is_environment_launcher(record_value: str) -> bool:
    """
    Detect generated command launchers outside site-packages.

    Windows installers commonly create paths such as:

        ../../Scripts/normalizer.exe
        ../../Scripts/idna.exe

    These launchers may contain the donor environment's interpreter
    path, so they must not be copied directly.
    """
    path = PurePosixPath(record_value)
    parts = [part.casefold() for part in path.parts]

    if "scripts" not in parts and "bin" not in parts:
        return False

    filename = path.name.casefold()

    return (
        filename.endswith(".exe")
        or filename.endswith(".cmd")
        or filename.endswith(".bat")
        or filename.endswith("-script.py")
        or "bin" in parts
    )


def classify_installed_file(
    record_value: str,
    source_path: str | Path,
    source_site_packages: str | Path,
) -> TransferKind:
    """Classify a RECORD-owned file before transfer."""
    if is_environment_launcher(record_value):
        return TransferKind.LAUNCHER
    path = PurePosixPath(record_value)
    if path.suffix.casefold() == ".pth":
        return TransferKind.PTH
    if any(part.casefold().endswith(".dist-info") for part in path.parts):
        return TransferKind.DISTRIBUTION_METADATA
    if path_is_within(source_path, source_site_packages):
        return TransferKind.PACKAGE_CONTENT
    return TransferKind.ENVIRONMENT


def validate_pth_file(path: str | Path, donor_environment: str | Path) -> None:
    """Reject executable or donor-specific path configuration."""
    try:
        lines = (
            Path(path)
            .read_text(
                encoding="utf-8",
                errors="replace",
            )
            .splitlines()
        )
    except OSError as exc:
        raise RuntimeError(f"Could not read .pth file: {path}: {exc}") from exc

    donor = normalized_absolute_path(donor_environment)
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(("import ", "import\t")):
            raise RuntimeError(f"Executable .pth statements are unsafe: {path}")
        expanded = os.path.expandvars(os.path.expanduser(line))
        if os.path.isabs(expanded):
            normalized = normalized_absolute_path(expanded)
            if path_is_within(normalized, donor) or normalized == donor:
                raise RuntimeError(f".pth file points at the donor environment: {path}")
            raise RuntimeError(f"Absolute paths in .pth files are unsafe: {path}")


def create_transfer_plan(
    package_name: str,
    version: str,
    candidates: list[dict[str, Any]],
) -> dict[str, Any]:
    """Create a dry-run transfer plan for one distribution."""
    donor = choose_donor(candidates)

    source_environment = normalized_absolute_path(donor["environment"])
    source_site_packages = normalized_absolute_path(donor["site_packages"])

    destination_environment = normalized_absolute_path(sys.prefix)
    destination_site_packages = normalized_absolute_path(target_site_packages())

    record_path = normalized_absolute_path(donor["record"])

    planned_files: list[dict[str, Any]] = []
    missing_files: list[str] = []
    unsafe_files: list[str] = []
    conflicts: list[str] = []

    total_size_bytes = 0
    site_packages_files = 0
    environment_files = 0
    environment_file_paths: list[dict[str, str]] = []
    skipped_bytecode_files = 0
    skipped_launcher_files: list[str] = []
    invalid_pth_files: list[str] = []

    try:
        record_file = open(
            record_path,
            encoding="utf-8",
            errors="replace",
            newline="",
        )
    except OSError as exc:
        raise RuntimeError(f"Could not read donor RECORD file: {exc}") from exc

    with record_file:
        reader = csv.reader(record_file)

        for row in reader:
            if not row:
                continue

            record_value = row[0].strip()

            if not record_value:
                continue

            if is_disposable_bytecode(record_value):
                skipped_bytecode_files += 1
                continue
            path_parts = record_path_parts(record_value)

            source_path = normalized_absolute_path(
                os.path.join(
                    source_site_packages,
                    *path_parts,
                )
            )

            destination_path = normalized_absolute_path(
                os.path.join(
                    destination_site_packages,
                    *path_parts,
                )
            )

            if not path_is_within(
                source_path,
                source_environment,
            ):
                unsafe_files.append(record_value)
                continue

            if not path_is_within(
                destination_path,
                destination_environment,
            ):
                unsafe_files.append(record_value)
                continue

            try:
                source_stat = os.stat(
                    source_path,
                    follow_symlinks=False,
                )
            except FileNotFoundError:
                missing_files.append(source_path)
                continue
            except OSError:
                missing_files.append(source_path)
                continue

            if not stat.S_ISREG(source_stat.st_mode):
                continue

            file_kind = classify_installed_file(
                record_value,
                source_path,
                source_site_packages,
            )
            if file_kind is TransferKind.LAUNCHER:
                skipped_launcher_files.append(record_value)
                continue
            if file_kind is TransferKind.PTH:
                try:
                    validate_pth_file(source_path, source_environment)
                except RuntimeError:
                    invalid_pth_files.append(record_value)
                    continue

            size_bytes = source_stat.st_size
            total_size_bytes += size_bytes

            if file_kind is not TransferKind.ENVIRONMENT:
                site_packages_files += 1
            else:
                environment_files += 1

                environment_file_paths.append(
                    {
                        "record_path": record_value,
                        "source": source_path,
                        "destination": destination_path,
                    }
                )

            if os.path.lexists(destination_path):
                conflicts.append(destination_path)

            planned_files.append(
                {
                    "record_path": record_value,
                    "source": source_path,
                    "destination": destination_path,
                    "size_bytes": size_bytes,
                    "category": file_kind.value,
                    "link_eligible": (file_kind is TransferKind.PACKAGE_CONTENT),
                }
            )

    source_drive = os.path.splitdrive(source_environment)[0].casefold()

    destination_drive = os.path.splitdrive(destination_environment)[0].casefold()

    return {
        "package": package_name,
        "version": version,
        "donor": donor["environment"],
        "source_site_packages": source_site_packages,
        "target_environment": destination_environment,
        "target_site_packages": destination_site_packages,
        "same_drive": source_drive == destination_drive,
        "planned_files": planned_files,
        "file_count": len(planned_files),
        "site_packages_files": site_packages_files,
        "environment_files": environment_files,
        "environment_file_paths": environment_file_paths,
        "skipped_bytecode_files": skipped_bytecode_files,
        "skipped_launcher_files": skipped_launcher_files,
        "invalid_pth_files": invalid_pth_files,
        "total_size_bytes": total_size_bytes,
        "missing_files": missing_files,
        "unsafe_files": unsafe_files,
        "conflicts": conflicts,
    }


def create_parent_directories(
    destination: Path,
    target_environment: Path,
    created_directories: set[Path],
) -> None:
    """Create missing parent directories and record them for rollback."""
    missing_directories: list[Path] = []
    current = destination.parent

    while not current.exists() and path_is_within(current, target_environment):
        missing_directories.append(current)
        current = current.parent

    for directory in reversed(missing_directories):
        directory.mkdir()
        created_directories.add(directory)


def rollback_transfer(
    created_files: list[Path],
    created_directories: set[Path],
) -> None:
    """Remove files and directories created by a failed transfer."""
    for created_file in reversed(created_files):
        try:
            created_file.unlink(missing_ok=True)
        except OSError:
            pass

    directories_by_depth = sorted(
        created_directories,
        key=lambda path: len(path.parts),
        reverse=True,
    )

    for directory in directories_by_depth:
        try:
            directory.rmdir()
        except OSError:
            # The directory may contain pre-existing or externally
            # created files, so it must not be forcibly removed.
            pass


def execute_transfer_plan(
    plan: dict[str, Any],
    progress_callback: Callable[[int, int], None] | None = None,
) -> dict[str, Any]:
    """
    Execute a previously validated package transfer plan.

    Hard links are preferred on the same volume. Physical copying is
    used when linking is unavailable.
    """
    if plan["conflicts"]:
        raise RuntimeError("Transfer refused because target conflicts exist.")

    if plan["missing_files"]:
        raise RuntimeError("Transfer refused because donor files are missing.")

    if plan["unsafe_files"]:
        raise RuntimeError("Transfer refused because unsafe RECORD paths exist.")

    if plan["environment_files"]:
        raise RuntimeError(
            "This package installs files outside site-packages. "
            "Environment-level files are not supported yet."
        )

    if plan.get("invalid_pth_files"):
        raise RuntimeError("Transfer refused because unsafe .pth files exist.")

    if not plan["planned_files"]:
        raise RuntimeError("The transfer plan contains no reusable files.")

    target_environment = Path(plan["target_environment"]).absolute()

    created_files: list[Path] = []
    created_directories: set[Path] = set()

    hardlinked_files = 0
    copied_files = 0
    transferred_bytes = 0

    total_files = len(plan["planned_files"])
    started_at = perf_counter()

    try:
        for position, file_entry in enumerate(
            plan["planned_files"],
            start=1,
        ):
            source = Path(file_entry["source"])
            destination = Path(file_entry["destination"])

            if destination.exists():
                raise RuntimeError(
                    f"Destination appeared during transfer: {destination}"
                )

            create_parent_directories(
                destination=destination,
                target_environment=target_environment,
                created_directories=created_directories,
            )

            transfer_method = "copy"

            if plan["same_drive"] and file_entry["link_eligible"]:
                try:
                    os.link(source, destination)
                    transfer_method = "hardlink"
                except OSError:
                    shutil.copyfile(source, destination)
            else:
                shutil.copyfile(source, destination)

            created_files.append(destination)
            transferred_bytes += file_entry["size_bytes"]

            if transfer_method == "hardlink":
                hardlinked_files += 1
            else:
                copied_files += 1

            if progress_callback is not None:
                progress_callback(position, total_files)

    except Exception:
        rollback_transfer(
            created_files=created_files,
            created_directories=created_directories,
        )
        raise

    elapsed_seconds = perf_counter() - started_at

    return {
        "package": plan["package"],
        "version": plan["version"],
        "files_transferred": len(created_files),
        "hardlinked_files": hardlinked_files,
        "copied_files": copied_files,
        "bytes_transferred": transferred_bytes,
        "elapsed_seconds": elapsed_seconds,
    }


def validate_installed_distribution(
    package_name: str,
    expected_version: str,
) -> None:
    """Validate transferred package metadata using a clean Python process."""
    validation_script = """
import importlib.metadata
import sys

package_name = sys.argv[1]
expected_version = sys.argv[2]

actual_version = importlib.metadata.version(package_name)

if actual_version != expected_version:
    raise SystemExit(
        f"Expected {expected_version}, found {actual_version}"
    )
"""

    completed = subprocess.run(
        [
            sys.executable,
            "-c",
            validation_script,
            package_name,
            expected_version,
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    if completed.returncode != 0:
        error = completed.stderr.strip() or completed.stdout.strip()

        raise RuntimeError(f"Transferred distribution validation failed: {error}")


def validate_complete_installation(
    package_versions: dict[str, str],
) -> None:
    """
    Validate that every transferred distribution is visible with the
    expected version, then run pip's dependency consistency check.
    """
    validation_script = """
import importlib.metadata
import json
import sys

expected_packages = json.loads(sys.argv[1])

failures = []

for package_name, expected_version in expected_packages.items():
    try:
        actual_version = importlib.metadata.version(package_name)
    except importlib.metadata.PackageNotFoundError:
        failures.append(
            f"{package_name}: distribution metadata not found"
        )
        continue

    if actual_version != expected_version:
        failures.append(
            f"{package_name}: expected {expected_version}, "
            f"found {actual_version}"
        )

if failures:
    raise SystemExit("\\n".join(failures))
"""

    metadata_check = subprocess.run(
        [
            sys.executable,
            "-c",
            validation_script,
            json.dumps(package_versions),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    if metadata_check.returncode != 0:
        error = (
            metadata_check.stderr.strip()
            or metadata_check.stdout.strip()
            or "Unknown metadata validation failure."
        )

        raise RuntimeError(f"Distribution metadata validation failed:\n{error}")

    dependency_check = subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "check",
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    if dependency_check.returncode != 0:
        error = (
            dependency_check.stdout.strip()
            or dependency_check.stderr.strip()
            or "pip check failed."
        )

        raise RuntimeError(f"Dependency validation failed:\n{error}")


def execute_installation_plan(
    installation_plan: dict[str, Any],
    progress_callback: (Callable[[str, int, int], None] | None) = None,
) -> dict[str, Any]:
    """
    Transfer every distribution in a complete installation plan.

    All package files belong to one transaction. If transferring or
    validating any distribution fails, every created file is removed.
    """
    if installation_plan["missing"]:
        raise RuntimeError("Installation refused because dependencies are missing.")

    if installation_plan["conflicts"]:
        raise RuntimeError("Installation refused because dependency conflicts exist.")

    if installation_plan["overlapping_files"]:
        raise RuntimeError(
            "Installation refused because distributions own overlapping target files."
        )

    package_plans = installation_plan["packages"]

    if not package_plans:
        raise RuntimeError("The installation plan contains no packages.")

    # Validate the complete plan before creating any target files.
    for package in package_plans:
        transfer = package["transfer"]

        if transfer["conflicts"]:
            raise RuntimeError(
                f"{package['name']} has {len(transfer['conflicts'])} target conflicts."
            )

        if transfer["missing_files"]:
            raise RuntimeError(
                f"{package['name']} has "
                f"{len(transfer['missing_files'])} missing source files."
            )

        if transfer["unsafe_files"]:
            raise RuntimeError(
                f"{package['name']} has {len(transfer['unsafe_files'])} unsafe paths."
            )

        if transfer["environment_files"]:
            raise RuntimeError(
                f"{package['name']} contains unsupported environment-level files."
            )

        if transfer.get("invalid_pth_files"):
            raise RuntimeError(f"{package['name']} contains unsafe .pth files.")

    target_environment = Path(
        package_plans[0]["transfer"]["target_environment"]
    ).absolute()

    created_files: list[Path] = []
    created_directories: set[Path] = set()

    hardlinked_files = 0
    copied_files = 0
    transferred_bytes = 0
    completed_files = 0

    total_files = sum(package["transfer"]["file_count"] for package in package_plans)

    started_at = perf_counter()

    try:
        for package in package_plans:
            package_name = package["name"]
            transfer = package["transfer"]

            for file_entry in transfer["planned_files"]:
                source = Path(file_entry["source"])
                destination = Path(file_entry["destination"])

                if destination.exists():
                    raise RuntimeError(
                        f"Destination appeared during installation: {destination}"
                    )

                create_parent_directories(
                    destination=destination,
                    target_environment=target_environment,
                    created_directories=created_directories,
                )

                transfer_method = "copy"

                if transfer["same_drive"] and file_entry["link_eligible"]:
                    try:
                        os.link(source, destination)
                        transfer_method = "hardlink"
                    except OSError:
                        shutil.copyfile(source, destination)
                else:
                    shutil.copyfile(source, destination)

                created_files.append(destination)
                transferred_bytes += file_entry["size_bytes"]
                completed_files += 1

                if transfer_method == "hardlink":
                    hardlinked_files += 1
                else:
                    copied_files += 1

                if progress_callback is not None:
                    progress_callback(
                        package_name,
                        completed_files,
                        total_files,
                    )

        expected_versions = {
            package["name"]: package["version"] for package in package_plans
        }

        validate_complete_installation(package_versions=expected_versions)

    except Exception:
        rollback_transfer(
            created_files=created_files,
            created_directories=created_directories,
        )
        raise

    elapsed_seconds = perf_counter() - started_at

    return {
        "packages_installed": len(package_plans),
        "files_transferred": len(created_files),
        "hardlinked_files": hardlinked_files,
        "copied_files": copied_files,
        "bytes_transferred": transferred_bytes,
        "elapsed_seconds": elapsed_seconds,
        "package_versions": {
            package["name"]: package["version"] for package in package_plans
        },
    }


def format_size(size_bytes: int) -> str:
    """Return a human-readable byte size."""
    size = float(size_bytes)

    for unit in ("B", "KB", "MB", "GB", "TB"):
        if size < 1024 or unit == "TB":
            if unit == "B":
                return f"{int(size)} {unit}"

            return f"{size:.2f} {unit}"

        size /= 1024

    return f"{size_bytes} B"
